.TH "BBEP" "1" "February 23, 2007" "Leonardo Amaral" "Scientific"
.SH "NAME"
bbep \- praat script for TextGrid Generation \- GUI
.SH "DESCRIPTION"
.PP 
This manual page documents briefly the \fBbeatextractor\fR command\&.

.PP 
This manual page was written for the Ubuntu distribution because the original program does not have a manual page\&.

.PP 
\fBbeatextractor\fR was adaptated from the BeatExtractor script that was conceived in order to produced automatic Vowel\-To Vowel segmentation running in Praat environnemt\&. The BBEP runs BeatExtractor from shell and optionally in a komander environnement that makes possible to segmentate multiples files at once, operation impossible in the Praat environnement\&. The original BeatExtractor script was written by Plinio Barbosa\&. The BBEP works in any complete bash environnemnt (including Windows + Cygwin), with praat, and for the GUI, Kommander is required too (at least kmdr\-executor)\&.

.SH "SEE ALSO"
.PP 
\fBbeatextractor\fR has a README file at /usr/share/doc/beatextractor/README\&.

.PP 
For further information, see the SetFon website (http://sourceforge\&.net/projects/setfon/)\&.

.SH "AUTHOR"
.PP 
This manual page was written by Leonardo Amaral <leleobhz@leleobhz\&.org> for the Ubuntu system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 any later version published by the Free Software Foundation\&.

.PP 
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL\&.

